[package]
name = "fluentd-log"
version = "0.0.0"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]

[dependencies]
derive_builder = "0.5"
failure = "0.1"
fruently = "0.10"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serializable_enum = "0.4"